### ISSUE TITLE
perf: Query the database on request

### ISSUE THREAD

**Issue by heyrict** [azzamsa/rust-graphql#3]
First, congratulations to you on finally making a working relay-styled graphql implementation. I skimmed through the patches you cherry-picked and found a point that may be improved.

---

https://github.com/azzamsa/nahla/blob/6db9e6f37547d1388ef163d9f465ed13a9d4ed21/src/user/repository/find_all_users.rs#L18

You seem to be computing all these three nodes `edges`, `pageInfo` and `totalCount` at once, no matter whether the users request for it.
I'm not sure about your use cases, but it may have some tiny to medium performance hit, and I would prefer returning an async-graphql object that fetches data upon request, e.g.

```rust
struct UserConnection {};

#[Object]
impl UserConnection {
    pub async fn edges() -> Result<Vec<User>>;
    pub async fn pageInfo() -> Result<PageInfo>;
    pub async fn totalCount() -> Result<u64>;
}
```

---

Despite the issue (AFAIK relay spec do not have a `totalCount` field), I think it could be a good reference material to implement relay-style graphql queries. :+1:

**Comment by azzamsa** [comment]
Hi, Zhenhui.
I am really happy about the input. Thank you for taking the time.

I have made another temporary repository that removes anything unrelated to our discussions. So that I can see the problem and the solution clearer.

This is our first implementation:
- https://github.com/azzamsa/nahla_tmp/commit/9d5f8e7f1c5736583295154f3ff8fe4bf0fef04e

I understand your improvement. But I am stuck in the implementation.
- https://github.com/azzamsa/nahla_tmp/commit/ceb4733af2250bde4c15a1a58d065218955a0e1d
- https://async-graphql.github.io/async-graphql/en/define_complex_object.html
- https://github.com/async-graphql/examples/blob/61384c8fa50e1395e50015b2be77b4bc6f5de4d2/models/books/src/lib.rs#L20

---

My steps are:

1. Separate each functionality in `Repository`

```diff
@@ -6,20 +6,27 @@ use crate::user::service::PageInfo;
 impl Repository {
     pub async fn find_all_users(
         &self,
-        _first: Option<i32>,
-        _after: Option<i32>,
-        _last: Option<i32>,
-        _before: Option<i32>,
-    ) -> Result<(Vec<entities::User>, PageInfo, i32), Error> {
-        let total_count: i32 = 10;
-
+        first: Option<i32>,
+        after: Option<i32>,
+        last: Option<i32>,
+        before: Option<i32>,
+    ) -> Result<Vec<entities::User>, Error> {
         let user = entities::User {
             id: 1,
             name: "Khawa".into(),
             full_name: None,
         };
         let users = [user].to_vec();
+        Ok(users)
+    }
 
+    pub async fn all_users_page_info(
+        &self,
+        first: Option<i32>,
+        after: Option<i32>,
+        last: Option<i32>,
+        before: Option<i32>,
+    ) -> Result<PageInfo, Error> {
         let page_info = PageInfo {
             has_next_page: false,
             has_previous_page: false,
@@ -27,6 +34,10 @@ impl Repository {
             end_cursor: Some("end".into()),
         };
 
-        Ok((users, page_info, total_count))
+        Ok(page_info)
+    }
+
+    pub async fn all_users_total_count(&self) -> Result<i32, Error> {
+        Ok(10)
     }
 }
```

2. Separate each functionality in `Service`

```diff
 #![allow(clippy::needless_collect)]
-
-use super::Service;
+use super::{PageInfo, Service};
+use crate::errors;
 use crate::errors::Error;
 use crate::user::model;
-use crate::user::model::{UserConnection, UserEdge};
+use crate::user::model::UserEdge;
 
 impl Service {
     pub async fn find_users(
@@ -12,25 +12,40 @@ impl Service {
         after: Option<i32>,
         last: Option<i32>,
         before: Option<i32>,
-    ) -> Result<UserConnection, Error> {
-        let (users, page_info, total_count) =
-            self.repo.find_all_users(first, after, last, before).await?;
+    ) -> Result<Vec<UserEdge>, Error> {
+        let users = self.repo.find_all_users(first, after, last, before).await?;
 
         let users_: Vec<model::User> = users.into_iter().map(|user| user.into()).collect();
         let user_edges: Vec<UserEdge> = users_
             .into_iter()
             .map(|user| {
                 let cursor = user.id;
-                UserEdge { node: user, cursor }
+                UserEdge {
+                    node: user,
+                    cursor: cursor,
+                }
             })
             .collect();
 
-        let user_connection = UserConnection {
-            edges: user_edges,
-            page_info: page_info.into(),
-            total_count,
-        };
+        Ok(user_edges)
+    }
+    pub async fn users_page_info(
+        &self,
+        first: Option<i32>,
+        after: Option<i32>,
+        last: Option<i32>,
+        before: Option<i32>,
+    ) -> Result<PageInfo, Error> {
+        let page_info = self
+            .repo
+            .all_users_page_info(first, after, last, before)
+            .await?;
+
+        Ok(page_info)
+    }
 
-        Ok(user_connection)
+    pub async fn users_total_count(&self) -> Result<i32, Error> {
+        let total_count = self.repo.all_users_total_count().await?;
+        Ok(total_count)
     }
 }
```

3. Make each `async_graphql:SimpleObject` `UserConnection` to async `Object`

Let port `total_count` only this time.

```diff
-#[derive(Debug, SimpleObject)]
 pub struct UserConnection {
     // A list of edges.
     pub edges: Vec<UserEdge>,
     pub total_count: i32,
 }
 
+#[Object]
+impl UserConnection {
+      pub async fn total_count(&self, ctx: &Context<'_>) -> async_graphql::Result<i32> {
+        let server_ctx = ctx.data::<Arc<ServerContext>>()?;
+        let result = server_ctx.user_service.users_total_count().await;
+
+        match result {
+            Ok(total_count) => Ok(total_count),
+            Err(err) => Err(Error::new(err.to_string())),
+        }
+    }
+}
+
```
---

Now, I had a problem with 3rd step.

1. Now the `Resolver` need to return `UserConnection` too. How the `/user/resolver` call the `total_count()` in UserConnection?

Something like this:
- https://github.com/azzamsa/nahla_tmp/blob/a9a2e7af8dcccd0b6fea45f13203ceb2afca4285/src/user/model/mod.rs#L45

```diff
 
 #[Object]
 impl UserConnection {
-      pub async fn total_count(&self, ctx: &Context<'_>) -> async_graphql::Result<i32> {
+    pub async fn edges(
+        &self,
+        ctx: &Context<'_>,
+        first: Option<i32>,
+        after: Option<i32>,
+        last: Option<i32>,
+        before: Option<i32>,
+    ) -> async_graphql::Result<Vec<UserEdge>> {
+        let server_ctx = ctx.data::<Arc<ServerContext>>()?;
+        let result = server_ctx
+            .user_service
+            .find_users(first, after, last, before)
+            .await;
+
+        match result {
+            Ok(user_edge) => Ok(user_edge),
+            Err(err) => Err(Error::new(err.to_string())),
+        }
+    }
+
+    pub async fn page_info(
+        &self,
+        ctx: &Context<'_>,
+        first: Option<i32>,
+        after: Option<i32>,
+        last: Option<i32>,
+        before: Option<i32>,
+    ) -> async_graphql::Result<PageInfo> {
+        let server_ctx = ctx.data::<Arc<ServerContext>>()?;
+        let result = server_ctx
+            .user_service
+            .users_page_info(first, after, last, before)
+            .await;
+
+        match result {
+            Ok(page_info) => Ok(page_info.into()),
+            Err(err) => Err(Error::new(err.to_string())),
+        }
+    }
+    pub async fn total_count(&self, ctx: &Context<'_>) -> async_graphql::Result<i32> {
         let server_ctx = ctx.data::<Arc<ServerContext>>()?;
         let result = server_ctx.user_service.users_total_count().await;

```

But I don't think I can call it from the `Resolver`.

2. If we solved the previous issue, then we have to include all the `edges`, `PageInfo`, and `total_count` in `Resolver` which also will be called every time the user uses `users` in the query.

Something like this:
- https://github.com/azzamsa/nahla_tmp/blob/a21e259a241890931f6264e571cfbe88feb36c6b/src/user/resolver.rs#L21

```diff
#[derive(Default)]
pub struct UserQuery;

#[Object]
impl UserQuery {
    pub async fn users(
        &self,
        ctx: &Context<'_>,
        first: Option<i32>,
        after: Option<i32>,
        last: Option<i32>,
        before: Option<i32>,
    ) -> FieldResult<UserConnection> {

         let server_ctx = ctx.data::<Arc<ServerContext>>()?;
 
-        let result = server_ctx
+        let edges = server_ctx
             .user_service
             .find_users(first, after, last, before)
-            .await;
+            .await?;
 
-        match result {
-            Ok(users) => Ok(users),
-            Err(err) => Err(Error::new(err.to_string())),
-        }
+        let page_info = server_ctx
+            .user_service
+            .users_page_info(first, after, last, before)
+            .await?;
+
+        let total_count = server_ctx.user_service.users_total_count().await?;
+
+        let user_connection = UserConnection {
+            edges,
+            page_info: page_info.into(),
+            total_count,
+        };
+
+        Ok(user_connection)
     }
 }
```

Would you like to give me more hints?

**Comment by heyrict** [comment]
Well, thank you for your detailed explanation. But sorry that I may not have enough time to inspect the full code until the end of this month. I'm not familiar with the Service/Resolver design, but I can give you some of my initial thoughts:

IMO, I think caching the fetched results to edges upon calling `edges` or `page_info` nodes could work around your issue. As the results are strictly tighted, I think [OnceCell](https://docs.rs/tokio/latest/tokio/sync/struct.OnceCell.html) may work to make sure database is only queried once for each instance of `UserConnection`.

```rust
pub struct UserConnection {
     // A list of edges.
     pub edges: OnceCell<Result<(Vec<UserEdge>, PageInfo)>>,
     pub params: UserConnectionParams, // first, last, etc.
 }
 
+#[Object]
+impl UserConnection {
    pub async fn edges(&self, ctx: &Context) -> Result<&Vec<UserEdge>> {
        self.cache.get_or_init(|| async { ctx.fetch_users(&self.params) }).await.map(|v| v[0])
    }
    pub async fn page_info(&self, ctx: &Context) -> Result<&PageInfo> {
        self.cache.get_or_init(|| async { ctx.fetch_users(&self.params) }).await.map(|v| v[1])
    }
    ...
}

#[Object]
impl Query {
    pub async fn users(...) -> Result<UserConnection> {
        Ok(UserConnection::new(UserConnectionParameters::new(...)))
    }
}
```

**Comment by azzamsa** [comment]
I try to implement without `OneCell` first. But I am stuck at `UserConnection`.

The `UserConnection` must use `&self` as first parameter, So I can't create `new` method without having this error:

```rust
  --> src/user/resolver.rs:35:32
   |
35 |         Ok(UserConnection::new(&self, ctx, params).await?)
   |                                ^^^^^ expected struct `UserConnection`, found `&UserQuery`
   |
   = note: expected reference `&UserConnection`
              found reference `&&UserQuery`
```

This is my current draft:
- https://github.com/azzamsa/nahla/commit/29db1d442fe2c10ad036d92a6d4884a4c2b1a73a

---

I can't do something like `Ok(UserConnection::new(ctx, params).await?)` here:

```rust
#[Object]
impl UserQuery {
    pub async fn users(
        &self,
        ctx: &Context<'_>,
        after: Option<String>,
        before: Option<String>,
        first: Option<i32>,
        last: Option<i32>,
    ) -> FieldResult<UserConnection> {
        let params = UserConnectionParams {
            first,
            after,
            last,
            before,
        };
        Ok(UserConnection::new(&self, ctx, params).await?)
````
Because each method in `UserConnection` need `&self`.

**Comment by heyrict** [comment]
Well, I dont think something like `UserConnection::new(&self, ctx, params).await` is correct.
`ctx` will be passed only when called in a `impl` block modified with `#[async_graphql::Object]`, so you won't need them in the object initialization. Also `&self` is not something that can be passed to another object, it would violate the lifetime restrictions in rust. `&self` will and should always point to the literal _self_.
And, do not use async `new` function. It is against the rust coding convention.

**Comment by azzamsa** [comment]
Hi @heyrict.

Sorry for taking too long to reply.
I think I found the simplest way to convert my implementation to async version.
The signature is similar to your suggestion https://github.com/azzamsa/rust-graphql/issues/3#issue-1162612839. Inspired by the `value()` function here https://async-graphql.github.io/async-graphql/en/define_complex_object.html.

What do you think?

**Comment by heyrict** [comment]
Well, the code looks great.

But as you fetches `(rows, page_info, total_count)` sequentially in `Repository.find_all_users()`, the performance impact described in https://github.com/azzamsa/rust-graphql/issues/3#issue-1162612839 isn't resolved. I think it would be ideal if you could implement these in a lower level.

```rust
pub struct PageInfo {
    pub first: Option<i32>,
    pub after: Option<Uuid>,
    pub last: Option<i32>,
    pub before: Option<Uuid>,
}

#[Object]
impl PageInfo {
    // Fetch has_next_page in PageInfo so that querying merely `{ users { edges }}` won't invoke unneeded aggregation db queries
    pub async fn has_next_page(&self) -> bool {
        query = format!(...);
        has_next_page = sqlx::query(&has_next_query).fetch_one(db).await.ok().get(0);
        has_next_page
    }
    ...
}
```

**Comment by azzamsa** [comment]
@heyrict I think I found the solution after trimming down the problem to the [smallest working example](https://github.com/async-graphql/async-graphql/issues/989#issuecomment-1191509166).

I have two approach:

1. With helper field in struct, that hidden from end-user using `skip`. https://github.com/azzamsa/rust-graphql/pull/6
2. With `look ahead`. https://github.com/azzamsa/rust-graphql/pull/5

What's your comments on this?

**Comment by heyrict** [comment]
That's great! If they work, both look good to go. 👍 

> I can't separate page info and edges since both are depends on each other. edges depends on page info

That's something that I was afraid could be a major blocker. It should be fine if you couldn't separate them.
